### ISSUE TITLE
Where's the file autoload.php ?

### ISSUE THREAD

**Issue by M4uRoDev** [openprovider/op-whmcs-sslpanel-bundle#1]

**Comment by theemstra** [comment]
There is none, the instructions for installation are mentioned in the [readme.md file](https://github.com/openprovider/op-whmcs-sslpanel-bundle)

**Comment by M4uRoDev** [comment]
Thanks!

I got it, now I have a problem trying to buy an SSL, do not direct me to SSL Panel, nowhere do I find the link to go there.
